export const filmes = [
    {titulo: "Underdog", nota: 4.7, duracao: 84, poster: "https://m.media-amazon.com/images/I/612lXhr7adL.jpg", genero:"Ação"},
    {titulo: "Honest Thief", nota: 6.0, duracao: 99, poster: "https://m.media-amazon.com/images/M/MV5BZjEwNjYyMTMtODc5Yi00NTg5LTkwMzAtZTkyOTcyNTFkMGIyXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_FMjpg_UX1000_.jpg", genero:"Ação"},
    {titulo: "Star Wars: Episode III - Revenge of the Sith", nota: 7.5, duracao: 140, poster: "https://m.media-amazon.com/images/I/61jCCwfO6HL.jpg", genero:"Ação"},
    {titulo: "Deadpool", nota: 8.0, duracao: 108, poster: "https://img.elo7.com.br/product/zoom/1E3BBAE/big-poster-do-filme-deadpool-tamanho-90x-0-cm-loot-op-007-marvel.jpg", genero:"Ação"},
    {titulo: "Minha Mãe é uma Peça", nota: 7.2, duracao: 84, poster: "https://i.pinimg.com/originals/ed/ff/ac/edffac2e5c812bb7db9b1de2412929bf.jpg", genero:"Comédia"},
    {titulo: "Todo Mundo em Pânico", nota: 6.5, duracao: 88, poster: "https://assetsgn.nowonline.com.br/assets/p25765_v_v8_ah.jpg", genero:"Comédia"},
    {titulo: "Te Peguei", nota: 5.1, duracao: 105, poster: "https://pbs.twimg.com/media/DbuU2hfWkAcOtn7.jpg:large", genero:"Comédia"},
    {titulo: "O Amor é Cego", nota: 8.3, duracao: 114, poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEPWhy_4mzcejPcbLItIAN4na9eZ0vyQ6y1g&usqp=CAU", genero:"Comédia"},
    {titulo: "Apollo 11", nota: 8.2, duracao: 93, poster: "https://br.web.img3.acsta.net/pictures/19/05/28/12/36/3294013.jpg", genero:"Documentário"},
    {titulo: "Kiss the Ground", nota: 8.3, duracao: 84, poster: "https://images.justwatch.com/poster/207487185/s592/kiss-the-ground", genero:"Documentário"},
    {titulo: "The Game Changers", nota: 7.9, duracao: 86, poster: "https://m.media-amazon.com/images/M/MV5BMzg4ZjMzOWEtZjBhZi00MzgxLWEzNmItYjVlYjY0MGQ5ZmM5XkEyXkFqcGdeQXVyNDExMzMxNjE@._V1_.jpg", genero:"Documentário"},
    {titulo: "American Factory", nota: 7.4, duracao: 110, poster: "https://m.media-amazon.com/images/M/MV5BNWFkMDY1MjItZmNkOS00MDg2LWFlMjMtZWU3YmM0MmY3MWM3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg", genero:"Documentário"},
    {titulo: "The Blue Lagoon", nota: 5.8, duracao: 104, poster: "https://www.themoviedb.org/t/p/original/k6KsThCeoxxHDbVnlHLdTlf5wsy.jpg", genero:"Drama"},
    {titulo: "Gone Girl", nota: 8.1, duracao: 149, poster: "https://www.themoviedb.org/t/p/original/qymaJhucquUwjpb8oiqynMeXnID.jpg", genero:"Drama"},
    {titulo: "The Revenant", nota: 8.0, duracao: 156, poster: "https://m.media-amazon.com/images/M/MV5BMDE5OWMzM2QtOTU2ZS00NzAyLWI2MDEtOTRlYjIxZGM0OWRjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg", genero:"Drama"},
    {titulo: "After", nota: 5.3, duracao: 103, poster: "https://i0.wp.com/1.bp.blogspot.com/-a058JODWa8s/W_2FFGuPzDI/AAAAAAAAXHc/qwBxy8Zx804zTZTgQSwZo8P2SQrRMzXFQCLcBGAs/s1600/Poster_After_Teaser.jpg?ssl=1", genero:"Drama"},
    {titulo: "Mary", nota: 4.4, duracao: 84, poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY2pJ2cxGLu4pjaL2Ro90SpRXJYc84OQBQdMrAO_urgJ7enm9MjxclnnG_Kk6lhxjps_A&usqp=CAU", genero:"Terror"},
    {titulo: "The Grudge", nota: 5.9, duracao: 91, poster: "https://www.omelete.com.br/imagens/cinema/news/grudge/poster.jpg", genero:"Terror"},
    {titulo: "Gretel & Hansel", nota: 5.4, duracao: 87, poster: "https://m.media-amazon.com/images/M/MV5BOTc1ODgyMTctMGQ1ZS00M2QxLTk1NmYtODY0ZGJiYmZkZWZjXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg", genero:"Terror"},
    {titulo: "The Nun", nota: 5.3, duracao: 94, poster: "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/78e3b466891157.5b26a37ceebf0.jpg", genero:"Terror"},
    {titulo: "100% Wolf", nota: 5.7, duracao: 96, poster: "https://m.media-amazon.com/images/M/MV5BYmRiYTM3ZGMtNzA1Yy00OWQ1LWE2ZGEtZTRiYzYyZDZjYWYwXkEyXkFqcGdeQXVyMjMwODE4ODI@._V1_.jpg", genero:"Família"},
    {titulo: "Woody Woodpecker", nota: 4.1, duracao: 91, poster: "https://m.media-amazon.com/images/M/MV5BNjJjMmRkNjYtNmJhNi00ZDM1LWEzMjMtOWZjNjgxODc1YmFlXkEyXkFqcGdeQXVyOTQyNTIzNjM@._V1_.jpg", genero:"Família"},
    {titulo: "Ferdinand", nota: 6.7, duracao: 108, poster: "https://m.media-amazon.com/images/M/MV5BMjI4Mjk0NzQwOF5BMl5BanBnXkFtZTgwNjg3MjI2MjI@._V1_FMjpg_UX1000_.jpg", genero:"Família"},
    {titulo: "Pets United", nota: 3.8, duracao: 89, poster: "https://m.media-amazon.com/images/M/MV5BMjI4Mjk0NzQwOF5BMl5BanBnXkFtZTgwNjg3MjI2MjI@._V1_FMjpg_UX1000_.jpg", genero:"Família"}
  ]